import bpy
import uuid
from enum import StrEnum
import logging
import json

import blender_utils
from agent_lib.agent import Agent, VisionAgent
import prompts

logger = logging.getLogger(__name__)


class BlenderSceneNotFound(Exception):
    "Raise when the blender scene is not found, while trying to open it"


class BlenderScene:
    """
    A class to manage and interact with a Blender scene, extracting scene hierarchy, camera renders, and descriptions
    using AI-based agents.

    Attributes:
        hierarchy_string (str): A string representation of the scene's object hierarchy.
        cameras_renders_description (list): A list of tuples, each containing a camera name and its corresponding AI-generated
                                            render description.
        scene_description (str): A textual description of the scene generated by an AI model.
    """

    def __init__(self, scene_file_name):
        """
        Initializes the BlenderScene object.

        Args:
            scene_file_name (str): The file path of the Blender scene to load.

        Raises:
            BlenderSceneNotFound: If the specified Blender scene file cannot be loaded.

        The initialization process involves:
        1. Loading the Blender scene from the provided file path.
        2. Extracting the object hierarchy from the scene.
        3. Rendering images using the first 4 cameras found in the scene.
        4. Using an AI agent to generate descriptions for each camera render.
        5. Generating a scene-level description using a separate AI agent.
        """

        #Open blende scene file
        try:
            bpy.ops.wm.open_mainfile(filepath=scene_file_name)
        except Exception as e:
            raise BlenderSceneNotFound from e
        logger.info(f"Loaded blender scene {scene_file_name}")

        # Initialize helper agents
        renders_description_agent = VisionAgent(
            model="gpt-4o",
            system_prompt=prompts.VISION_IMAGE_DESCRIPTION_SYSTEM_PROMPT,
        )
        scene_description_agent = Agent(
            model="gpt-4o",
            system_prompt=prompts.SCENE_DESCRIPTION_SYSTEM_PROMPT,
        )

        #Get hierarchy string
        self.hierarchy_string = blender_utils.get_all_objects_hierarchy()

        #Get scene static information
        raw_scene_info_dict = blender_utils.get_scene_static_info()
        camera_list = raw_scene_info_dict["cameras"]

        # Render image from each camera and get description of it
        camera_list = camera_list[:4]  # Take only 4 first cameras
        self.cameras_renders_description = []
        for camera in camera_list:
            render_filename = str(uuid.uuid4())
            blender_utils.render_image(render_filename, camera)
            render_description, _ = renders_description_agent.inference(
                prompt=prompts.RENDER_DESCCRIPTION_PROMPT, image_path=render_filename
            )
            self.cameras_renders_description.append((camera, render_description))
            renders_description_agent.clear_converstation()

        scene_info_string = json.dumps(raw_scene_info_dict)

        self.scene_description, _ = scene_description_agent.inference(scene_info_string)
